version: 2.1

parameters:
  run:
    type: enum
    enum: [build, regression]
    default: build

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: echo "this is the build job"
  test:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: echo "this is the test job"
  regression:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: echo "regression"

workflows:
  regression_pack_cron:
    when: [ regression, << pipeline.parameters.action >> ]
    jobs:
      - build
      - test
      - regression

  build_and_test:
    unless: [ build, << pipeline.parameters.action >> ]
    jobs:
      - build
      - test