version: 2.1

parameters:
  run:
    type: boolean
    default: false

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: echo "this is the build job"
  test:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: echo "this is the test job"
  regression:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: echo "regression"

# Orchestrate our job run sequence

jobs_list: &jobs_list
 - build
 - test
 - regression


workflows:
  regression_pack_cron:
    triggers:
      - schedule:
          cron: '0 8,10,12,14,16 * * 1-5'
          filters:
            branches:
              only: main
    jobs:
      - *jobs_list

  regression_pack_manual:
    when: << pipeline.parameters.run >>
    jobs:
      - *jobs_list

  build_and_test:
    unless: << pipeline.parameters.run >>
    jobs:
      - build
      - test